### ISSUE TITLE
Does not show after installing

### ISSUE THREAD

**Issue by lazeravik** [XhmikosR/perfmonbar#15]
I am using windows 10 2004 x64
After installing it is not showing in the taskbar right click 

![image](https://user-images.githubusercontent.com/2894306/90863369-88f72600-e3ac-11ea-8c97-58454b4acc9f.png)

**Comment by wpa1160** [comment]
> 
> 
> I am using windows 10 2004 x64
> After installing it is not showing in the taskbar right click
> 
> ![image](https://user-images.githubusercontent.com/2894306/90863369-88f72600-e3ac-11ea-8c97-58454b4acc9f.png)

Confirmed on same OS build

**Comment by d0tAlexX** [comment]
Having the same issue on Windows 10 Pro Build: 2004 x64
A shame because I was using this just fine until I reformatted and updated my PC.

**Comment by XhmikosR** [comment]
A restart should fix it. Or restarting explorer.exe manually. I personally cannot reproduce this.

**Comment by d0tAlexX** [comment]
> 
> 
> A restart should fix it. Or restarting explorer.exe manually. I personally cannot reproduce this.

Thanks for the reply. Still having the same issue. Restarted the PC. Restarted explorer.exe manually and also ended explorer.exe and ran explorer.exe again. Enabling Perfomance Monitoring Toolbar shows nothing. you can only resize but it's a blank area.

This is on a fresh install of Win 10 Pro Sep2020 build and updating to the 2004 build.

**Comment by XhmikosR** [comment]
Sorry, I cannot reproduce it :/

What I have noticed is that sometimes after installing Perfmonbar for the first time, I have to right click twice to see the new toolbar, but apart from that it always shows up.

**Comment by wpa1160** [comment]
I just installed it again and restarting Explorer and right-clicking the taskbar multiple times did the trick and now it is working.

Restarting Explorer directly after setup using Ctrl+Shift however results in a never-ending crash loop.

Application log contains application error 1000...

Faulting application name: explorer.exe, version: 10.0.19041.488, time stamp: 0xb1a44bf9
Faulting module name: KERNELBASE.dll, version: 10.0.19041.488, time stamp: 0x5b4a3325
Exception code: 0xc0000602
Fault offset: 0x000000000010b3cc
Faulting process id: 0xeb4
Faulting application start time: 0x01d6a1416ccb6c87
Faulting application path: C:\WINDOWS\explorer.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 2bf5b699-02bc-41fb-a180-91402d4c54a3
Faulting package full name: 
Faulting package-relative application ID: 

...followed by Event 1002, Winlogon:
The shell stopped unexpectedly and explorer.exe was restarted.

I'm not sure if I would call that a bug since exiting Explorer is not common and it only occurs one time.

**Comment by XhmikosR** [comment]
The crash is unrelated to Perfmobar as you can see from the above message which is pointing to kernelbase.dll.

**Comment by KeZa81** [comment]
Hi, when fix for Windows 7 bc the newest version still not seeing anything in taskbar or is there any fix for it already?

**Comment by Gideon-Felt** [comment]
I restarted Explorer to resolve this, Hopefully, I dont have to do it with each reboot. (Latest Windows 10 Pro)

**Comment by XhmikosR** [comment]
Closing for now.
